In [27]:
import numpy as np

In [28]:
#создаем матрицу оценок фильмов
X=np.zeros((6, 7))
X = np.array([[4,4,5,0,0,0,0], [5,5,3,4,3,0,0], [0,0,0,4,4,0,0], [0,0,0,5,4,5,3], [0,0,0,0,0,5,5], [0,0,0,0,0,4,4]])

In [29]:
#находим сингулярное разложение
U, s, V = np.linalg.svd(X, full_matrices=True)

In [30]:
U


array([[  3.12588157e-01,   4.88299765e-01,  -4.97486928e-01,
         -6.42399264e-01,  -6.06788790e-02,  -8.21965453e-17],
       [  5.81592898e-01,   5.04410043e-01,   3.39133215e-02,
          6.34303396e-01,   6.18813194e-02,   8.51855106e-17],
       [  2.91075769e-01,   7.31204099e-03,   5.79298849e-01,
         -2.32962739e-01,  -7.24819038e-01,  -5.55172221e-17],
       [  5.77180773e-01,  -3.75701377e-01,   3.15581314e-01,
         -3.03696910e-01,   5.77829951e-01,  -3.37590837e-17],
       [  2.98548926e-01,  -4.72363581e-01,  -4.39080193e-01,
          1.53175607e-01,  -2.85031755e-01,  -6.24695048e-01],
       [  2.38839141e-01,  -3.77890864e-01,  -3.51264154e-01,
          1.22540486e-01,  -2.28025404e-01,   7.80868809e-01]])

In [31]:
#вектор весов факторов
s

array([  1.26226575e+01,   1.06683922e+01,   7.29730704e+00,
         1.64107896e+00,   9.53988881e-01,   3.30004874e-17])

In [32]:
V

array([[ 0.32943278,  0.32943278,  0.2620462 ,  0.50516926,  0.41336817,
         0.42257386,  0.33112231],
       [ 0.41948676,  0.41948676,  0.37069587,  0.01578321,  0.00371872,
        -0.5391523 , -0.46871969],
       [-0.2494593 , -0.2494593 , -0.32692809,  0.55236202,  0.50446837,
        -0.27716403, -0.36365657],
       [ 0.36678304,  0.36678304, -0.79769844,  0.05293961, -0.14851717,
        -0.15992196,  0.21019662],
       [ 0.06990761,  0.06990761, -0.12342957,  0.24884869, -0.42171601,
         0.57850712, -0.63289054],
       [-0.71329073,  0.69789665,  0.01231527,  0.04002461, -0.04002461,
        -0.02001231,  0.02001231],
       [-0.07123497, -0.16370203,  0.1879496 ,  0.6108362 , -0.6108362 ,
        -0.3054181 ,  0.3054181 ]])

In [33]:
#превращаем вектор весов матрицу весов
S = np.zeros((6, 7))

In [34]:
S[:6,:6]=np.diag(s)
S

array([[  1.26226575e+01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   1.06683922e+01,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   7.29730704e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.64107896e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   9.53988881e-01,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   3.30004874e-17,
          0.00000000e+00]])

In [35]:
#пробуем восстанавливать исходную матрицу
np.dot(U, np.dot(S, V))

array([[  4.00000000e+00,   4.00000000e+00,   5.00000000e+00,
          9.04398596e-16,   9.20373504e-16,   5.87028089e-16,
          5.95694946e-16],
       [  5.00000000e+00,   5.00000000e+00,   3.00000000e+00,
          4.00000000e+00,   3.00000000e+00,  -6.02155430e-16,
         -2.84405778e-16],
       [  3.57220994e-16,   7.13285194e-17,   4.31472232e-16,
          4.00000000e+00,   4.00000000e+00,  -1.87363603e-15,
         -1.32959913e-15],
       [  1.47433400e-15,   9.91229891e-16,   2.29874676e-15,
          5.00000000e+00,   4.00000000e+00,   5.00000000e+00,
          3.00000000e+00],
       [  7.09455292e-16,   3.63118858e-16,   6.09097584e-16,
         -1.14174352e-15,  -1.38769170e-15,   5.00000000e+00,
          5.00000000e+00],
       [  6.07200061e-16,   3.49176919e-16,   8.32138391e-16,
         -8.10873899e-16,  -8.13583095e-16,   4.00000000e+00,
          4.00000000e+00]])

In [36]:
Y=np.dot(U, np.dot(S, V))

In [37]:
#вычисляем ошибку приближения со всеми факторами
np.linalg.norm(X-Y)

1.3677535415069609e-14

In [38]:
#обнуляем 5-ый фактор
S[4,4]=0

In [39]:
Y=np.dot(U, np.dot(S, V))

In [40]:
np.linalg.norm(X-Y)

0.95398888134339599

In [44]:
X-Y

array([[-0.00404674, -0.00404674,  0.00714496, -0.0144051 ,  0.02441186,
        -0.03348803,  0.03663612],
       [ 0.00412693,  0.00412693, -0.00728655,  0.01469056, -0.02489562,
         0.03415164, -0.03736212],
       [-0.04833897, -0.04833897,  0.08534776, -0.17207123,  0.29160368,
        -0.40001991,  0.43762438],
       [ 0.0385361 ,  0.0385361 , -0.06803973,  0.13717618, -0.23246815,
         0.3188982 , -0.3488767 ],
       [-0.01900908, -0.01900908,  0.03356261, -0.06766622,  0.11467181,
        -0.15730599,  0.17209378],
       [-0.01520726, -0.01520726,  0.02685009, -0.05413298,  0.09173745,
        -0.12584479,  0.13767502]])

In [26]:
#обнуляем 4-ый фактор
S[3,3]=0
Y=np.dot(U, np.dot(S, V))
np.linalg.norm(X-Y)/(6*7)

0.045195687823748068

In [16]:
from sklearn.decomposition import NMF

In [17]:
#инициализируем праметры неотрицательной матричной факторизации с тремя факторами
model = NMF(n_components=3, init='random', random_state=0)


In [18]:
#применяем модель к матрице оценок фильмов
model.fit(X) 


NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0,
  max_iter=200, n_components=3, random_state=0, shuffle=False, solver='cd',
  tol=0.0001, verbose=0)

In [19]:
#извлекаем компоненты 
W = model.fit_transform(X);
H = model.components_;

In [20]:
#зрители-факторы
W


array([[ 2.24793179,  0.        ,  0.        ],
       [ 2.23118348,  1.66417342,  0.        ],
       [ 0.        ,  1.91022987,  0.        ],
       [ 0.        ,  2.17779586,  1.98547926],
       [ 0.        ,  0.        ,  2.58505415],
       [ 0.        ,  0.        ,  2.06804332]])

In [21]:
#факторы-фильмы
H

array([[ 1.97582315,  1.97582315,  1.78771163,  0.06530907,  0.        ,
         0.        ,  0.        ],
       [ 0.08820566,  0.08820566,  0.        ,  2.22716484,  1.91238711,
         0.18750422,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.01994477,  0.        ,
         2.03430582,  1.82223255]])

In [22]:
#восстанавливаем исходную матрицу
Y=np.dot(W,H)
Y

array([[ 4.44151567,  4.44151567,  4.0186538 ,  0.14681033,  0.        ,
         0.        ,  0.        ],
       [ 4.55521349,  4.55521349,  3.98871265,  3.85210505,  3.18254379,
         0.31203953,  0.        ],
       [ 0.16849309,  0.16849309,  0.        ,  4.2543968 ,  3.65309897,
         0.35817615,  0.        ],
       [ 0.19209393,  0.19209393,  0.        ,  4.88991029,  4.16478872,
         4.44741791,  3.61800494],
       [ 0.        ,  0.        ,  0.        ,  0.0515583 ,  0.        ,
         5.2587907 ,  4.71056983],
       [ 0.        ,  0.        ,  0.        ,  0.04124664,  0.        ,
         4.20703256,  3.76845586]])

In [45]:
#находим суммарную ошибку
np.linalg.norm(X-Y)

0.95398888134339599

In [24]:
X-Y

array([[-0.44151567, -0.44151567,  0.9813462 , -0.14681033,  0.        ,
         0.        ,  0.        ],
       [ 0.44478651,  0.44478651, -0.98871265,  0.14789495, -0.18254379,
        -0.31203953,  0.        ],
       [-0.16849309, -0.16849309,  0.        , -0.2543968 ,  0.34690103,
        -0.35817615,  0.        ],
       [-0.19209393, -0.19209393,  0.        ,  0.11008971, -0.16478872,
         0.55258209, -0.61800494],
       [ 0.        ,  0.        ,  0.        , -0.0515583 ,  0.        ,
        -0.2587907 ,  0.28943017],
       [ 0.        ,  0.        ,  0.        , -0.04124664,  0.        ,
        -0.20703256,  0.23154414]])

In [25]:
# на точность приближения влияют параметры модели (например, можно увеличить число факторов)